services:
  mysql:
    container_name: scenario
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: scenario
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    ports:
      - 13306:3306
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"